# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            GrooveStomp
tagline:          'Online Musings'
description:      'Online Musings'
url:              http://hyde.getpoole.com

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde

profile:
  github:         https://github.com/GrooveStomp
  twitter:        https://twitter.com/GrooveStomp
  stackoverflow:  https://stackoverflow.com/users/321897/groovestomp
  bitbucket:      https://bitbucket.org/GrooveStomp
  flickr:         https://secure.flickr.com/photos/groovestomp/
  icon:
    groovestomp:  /public/groovestomp_icon.jpg
    aaron:        /public/profile.jpg
