# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            GrooveStomp
name:             'GrooveStomp: Online Ruminations'
tagline:          Online Ruminations
description:      Thoughts on matters mostly related to software development
url:              http://www.groovestomp.com

author:
  name:           Aaron Oman
  url:            http://www.groovestomp.com/about

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://github.com/poole/hyde

boardgames:       http://boardgames.groovestomp.com
photos:           https://groovestomp.smugmug.com

profile:
  twitter:        https://twitter.com/GrooveStomp
  github:         https://github.com/GrooveStomp
  bitbucket:      https://bitbucket.org/GrooveStomp
  icon:
    groovestomp:  /public/groovestomp_icon.jpg
    aaron:        /public/profile.jpg

exclude:          [vendor, env]